### ISSUE TITLE
How to generate image from my own caption?

### ISSUE THREAD

**Issue by jaykshirsagar05** [Kyfafyd/MirrorGAN#1]
I aim to use this model implementation as a black box and to input my own caption and should get than an image as an output.
Thanks

**Comment by Kyfafyd** [comment]
Well, you can input the caption for the output image. maybe you can refer to https://github.com/Kyfafyd/MirrorGAN#test
https://github.com/Kyfafyd/MirrorGAN/blob/be65f4bbfcdfb15be55fd9baf7228a59e984e450/GLAM/main.py#L140
