### ISSUE TITLE
do you have the flower preprocessed metadata?

### ISSUE THREAD

**Issue by zjuirene** [Kyfafyd/MirrorGAN#2]
rt.

**Comment by Kyfafyd** [comment]
I wonder which flower dataset do you mean? Can you make it clear?

**Comment by zjuirene** [comment]
> I wonder which flower dataset do you mean? Can you make it clear?

I want to train on the Oxford 102 Flowers dataset. if there is the preprocessed metadata like the birds data

**Comment by Kyfafyd** [comment]
Thanks for clarify the issue, maybe you can refer to this repo for Oxford flowers dataset https://github.com/yejg2017/stackgan-text2image <https://github.com/yejg2017/stackgan-text2image>
