### ISSUE TITLE
What are the functions of list1.txt and list2.txt in preprocess.py？

### ISSUE THREAD

**Issue by kj-wu** [Kyfafyd/MirrorGAN#3]
I'm trying to train with my own dataset, but I'm having some problems with preprocessing，Can you tell me What are the functions of list1.txt and list2.txt in preprocess.py？

**Comment by Kyfafyd** [comment]
Thanks for interest!
The script `preprocess.py` is used as a demo for generate discriptions for every image. I just use the image name as the description. So you can use much more accurate text for training.

**Comment by Kyfafyd** [comment]
> I'm trying to train with my own dataset, but I'm having some problems with preprocessing，Can you tell me What are the functions of list1.txt and list2.txt in preprocess.py？

Thanks for interest!
The script `preprocess.py` is used as a demo for generate discriptions for every image. I just use the image name as the description. So you can use much more accurate text for training.
