### ISSUE TITLE
Issues with train

### ISSUE THREAD

**Issue by GroundFinchOfGalapagos** [Kyfafyd/MirrorGAN#4]
I‘d like to train the model and when I try to run the GLAM main.py, the error occurs, I find it on the google,but i failed to solve the problem,  can you teach me why this error occur and what can I do to solve it. Thanks!
 
![image](https://user-images.githubusercontent.com/53991577/95723313-98596800-0ca7-11eb-89c8-55f7c2308b93.png)

**Comment by Kyfafyd** [comment]
> I‘d like to train the model and when I try to run the GLAM main.py, the error occurs, I find it on the google,but i failed to solve the problem, can you teach me why this error occur and what can I do to solve it. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/53991577/95723313-98596800-0ca7-11eb-89c8-55f7c2308b93.png)

are you running on bird dataset?

**Comment by WhereISmyroad** [comment]
> > I‘d like to train the model and when I try to run the GLAM main.py, the error occurs, I find it on the google,but i failed to solve the problem, can you teach me why this error occur and what can I do to solve it. Thanks!
> > ![image](https://user-images.githubusercontent.com/53991577/95723313-98596800-0ca7-11eb-89c8-55f7c2308b93.png)
> 
> are you running on bird dataset?

Hello sir
     I train Image caption 700 times in my computer, but  when I turn to train MirrorGAN get cap_loss : 423. How to distinguish whether the image caption model is correct?
     Thanks

**Comment by Kyfafyd** [comment]
> > > I‘d like to train the model and when I try to run the GLAM main.py, the error occurs, I find it on the google,but i failed to solve the problem, can you teach me why this error occur and what can I do to solve it. Thanks!
> > > ![image](https://user-images.githubusercontent.com/53991577/95723313-98596800-0ca7-11eb-89c8-55f7c2308b93.png)
> > 
> > 
> > are you running on bird dataset?
> 
> Hello sir
> I train Image caption 700 times in my computer, but when I turn to train MirrorGAN get cap_loss : 423. How to distinguish whether the image caption model is correct?
> Thanks

Thanks for discussing!
I would like to learn the Image Caption loss you get is?

**Comment by WhereISmyroad** [comment]
Thank you for your reply
  I use the code you provided. 
  How do you modify it to make the generation model 5450x/
 {I change the .json， but I think it is wrong to do so}
Thanks

**Comment by Kyfafyd** [comment]
> Thank you for your reply
> I use the code you provided.
> How do you modify it to make the generation model 5450x/
> {I change the .json， but I think it is wrong to do so}
> Thanks

Sorry for reply so late...
Can you describe your problem more clearly？

**Comment by WhereISmyroad** [comment]
> > Thank you for your reply
> > I use the code you provided.
> > How do you modify it to make the generation model 5450x/
> > {I change the .json， but I think it is wrong to do so}
> > Thanks
> 
> Sorry for reply so late...
> Can you describe your problem more clearly？

Thanks for your reply
      The model you provided is shown below，how to change to 5450x300 when training STREAM
![image](https://user-images.githubusercontent.com/48115151/100506171-f7b3fe80-31a7-11eb-94e5-ed3d10e69561.png)

Thank you very much.

**Comment by WhereISmyroad** [comment]
> > Thank you for your reply
> > I use the code you provided.
> > How do you modify it to make the generation model 5450x/
> > {I change the .json， but I think it is wrong to do so}
> > Thanks
> 
> Sorry for reply so late...
> Can you describe your problem more clearly？

Thanks for your reply
      The text encoder model you provided is 5053x300，how to change to 5450x300 when training STREAM
Thank you very much.

**Comment by WhereISmyroad** [comment]
> > Thank you for your reply
> > I use the code you provided.
> > How do you modify it to make the generation model 5450x/
> > {I change the .json， but I think it is wrong to do so}
> > Thanks
> 
> Sorry for reply so late...
> Can you describe your problem more clearly？

Thanks for your reply
The rnn_decoder.ckpt model you provided is 5453x300，how to change to 5450x300 when training STREAM
Thank you very much.

**Comment by Kyfafyd** [comment]
> > > Thank you for your reply
> > > I use the code you provided.
> > > How do you modify it to make the generation model 5450x/
> > > {I change the .json， but I think it is wrong to do so}
> > > Thanks
> > 
> > 
> > Sorry for reply so late...
> > Can you describe your problem more clearly？
> 
> Thanks for your reply
> The rnn_decoder.ckpt model you provided is 5453x300，how to change to 5450x300 when training STREAM
> Thank you very much.

I think this size mismatch is caused by using different dataset which has different vocabulary length.
As for solution, you may pretrain STREAM model and STEM model at first.
You can refer to this [pretrain section](https://github.com/Kyfafyd/MirrorGAN#pretrain) in readme file.

**Comment by GroundFinchOfGalapagos** [comment]
thank for your reply,
there was some problem with this mailbox
so I haven't see these message until now
I use the model provided by Attn-GAN,it's 5450x300
and we re-train  a new model which can match the size
very sorry for apply so late
thank you very much for the discuss










At 2020-11-29 17:12:40, "Zhao Wang" <notifications@github.com> wrote:

Thank you for your reply
I use the code you provided.
How do you modify it to make the generation model 5450x/
{I change the .json， but I think it is wrong to do so}
Thanks

Sorry for reply so late...
Can you describe your problem more clearly？

Thanks for your reply
The rnn_decoder.ckpt model you provided is 5453x300，how to change to 5450x300 when training STREAM
Thank you very much.

I think this size mismatch is caused by using different dataset.
As for solution, you may pretrain STREAM model and STEM model at first.
You can refer to this pretrain section in readme file.
