### ISSUE TITLE
Question with pretrained model

### ISSUE THREAD

**Issue by WhereISmyroad** [Kyfafyd/MirrorGAN#6]
Hello sir
     Do you have a cub / coco pretrained model?The author did not provide，I just want to use it for comparative experiments
【MirrorGAN pretrained model, not the stem / stream model】
Thanks

**Comment by Kyfafyd** [comment]
> Hello sir
> Do you have a cub / coco pretrained model?The author did not provide，I just want to use it for comparative experiments
> 【MirrorGAN pretrained model, not the stem / stream model】
> Thanks

I am sorry that I have not pretrained yet. You can try by yourself.
